# Generated by Django 4.1 on 2023-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_history",
            name="history",
        ),
        migrations.AddField(
            model_name="user_history",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name="user_history",
            table="my_model",
        ),
    ]
