# Generated by Django 4.1 on 2023-04-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_user_history_history_user_history_data_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user_history",
            table=None,
        ),
    ]
